version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 256m
    restart: unless-stopped
